# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/widget/widget.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/widget/widget.proto',
  package='widget',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/widget/widget.proto\x12\x06widget\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n\x06Widget\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12/\n\x0b\x63reate_time\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1d\n\rWidgetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2\xd4\x01\n\x07Widgets\x12.\n\x03Get\x12\x15.widget.WidgetRequest\x1a\x0e.widget.Widget\"\x00\x12*\n\x06\x43reate\x12\x0e.widget.Widget\x1a\x0e.widget.Widget\"\x00\x12\x32\n\x04List\x12\x16.google.protobuf.Empty\x1a\x0e.widget.Widget\"\x00\x30\x01\x12\x39\n\x06\x44\x65lete\x12\x15.widget.WidgetRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WIDGET = _descriptor.Descriptor(
  name='Widget',
  full_name='widget.Widget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='widget.Widget.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='widget.Widget.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='widget.Widget.create_time', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=191,
)


_WIDGETREQUEST = _descriptor.Descriptor(
  name='WidgetRequest',
  full_name='widget.WidgetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='widget.WidgetRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=222,
)

_WIDGET.fields_by_name['create_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Widget'] = _WIDGET
DESCRIPTOR.message_types_by_name['WidgetRequest'] = _WIDGETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Widget = _reflection.GeneratedProtocolMessageType('Widget', (_message.Message,), {
  'DESCRIPTOR' : _WIDGET,
  '__module__' : 'proto.widget.widget_pb2'
  # @@protoc_insertion_point(class_scope:widget.Widget)
  })
_sym_db.RegisterMessage(Widget)

WidgetRequest = _reflection.GeneratedProtocolMessageType('WidgetRequest', (_message.Message,), {
  'DESCRIPTOR' : _WIDGETREQUEST,
  '__module__' : 'proto.widget.widget_pb2'
  # @@protoc_insertion_point(class_scope:widget.WidgetRequest)
  })
_sym_db.RegisterMessage(WidgetRequest)



_WIDGETS = _descriptor.ServiceDescriptor(
  name='Widgets',
  full_name='widget.Widgets',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=225,
  serialized_end=437,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='widget.Widgets.Get',
    index=0,
    containing_service=None,
    input_type=_WIDGETREQUEST,
    output_type=_WIDGET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='widget.Widgets.Create',
    index=1,
    containing_service=None,
    input_type=_WIDGET,
    output_type=_WIDGET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='widget.Widgets.List',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_WIDGET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='widget.Widgets.Delete',
    index=3,
    containing_service=None,
    input_type=_WIDGETREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WIDGETS)

DESCRIPTOR.services_by_name['Widgets'] = _WIDGETS

# @@protoc_insertion_point(module_scope)
